name: "Build docker image"
on:
  push:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  build-main-image:
    name: Build sncd image
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_REGISTRY }}/sncd:main"
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            HOST=sncd.ru

  build-cc-image:
    name: Build cc.syncended.dev image
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_REGISTRY }}/sncd:cc"
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            HOST=cc.syncended.dev